[package]
name = "entidb_py"
version = "2.0.0-alpha.1"
edition = "2021"

[lib]
name = "entidb"
crate-type = ["cdylib"]

[features]
default = ["encryption"]
encryption = ["entidb_core/encryption"]

[dependencies]
entidb_core.workspace = true
pyo3.workspace = true
