# Rustfmt configuration for EntiDB
# See: https://rust-lang.github.io/rustfmt/

edition = "2021"

# Formatting options
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"

# Import organization (stable options only)
reorder_imports = true
reorder_modules = true

# Misc (stable options only)
use_small_heuristics = "Default"
use_field_init_shorthand = true
force_explicit_abi = true

