name: entidb_dart
description: Dart bindings for EntiDB - an embedded entity database engine with ACID transactions and CBOR storage.
version: 2.0.0-alpha.3
repository: https://github.com/Tembocs/entidb
homepage: https://github.com/Tembocs/entidb
documentation: https://github.com/Tembocs/entidb/tree/main/bindings/dart/entidb_dart

topics:
  - database
  - embedded-database
  - nosql
  - cbor

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
